# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            managers=[
                ('clients', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('tracking_number', models.IntegerField()),
                ('shipping_address', models.TextField()),
                ('shipping_latitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('shipping_longitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivered_date', models.DateTimeField(null=True)),
                ('client_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtest.Client')),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
            managers=[
                ('states', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtest.Orders')),
                ('state_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtest.States')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            managers=[
                ('vendors', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='state_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtest.States'),
        ),
        migrations.AddField(
            model_name='orders',
            name='vendor_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtest.Vendor'),
        ),
    ]
