# Generated by Django 2.0 on 2017-12-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='states',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
