# Generated by Django 2.0 on 2017-12-27 14:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0002_auto_20171227_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('shipping_address', models.TextField()),
                ('shipping_latitude', models.IntegerField()),
                ('shipping_longitude', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivered_date', models.DateTimeField()),
                ('client_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtest.Client')),
                ('state_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtest.States')),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtest.Orders')),
                ('state_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtest.States')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('address', models.TextField()),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='vendor_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webtest.Vendor'),
        ),
    ]
