# Generated by Django 2.0 on 2017-12-29 15:30

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0003_auto_20171227_0903'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='client',
            managers=[
                ('clients', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='states',
            managers=[
                ('states', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='vendor',
            managers=[
                ('vendors', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipping_latitude',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipping_longitude',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
    ]
