# Generated by Django 2.0 on 2017-12-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0004_auto_20171229_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='tracking_number',
            field=models.IntegerField(default=1234),
            preserve_default=False,
        ),
    ]
