# Generated by Django 2.0 on 2017-12-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0005_orders_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivered_date',
            field=models.DateTimeField(null=True),
        ),
    ]
