# Generated by Django 2.0 on 2017-12-31 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0007_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
